<a href="https://colab.research.google.com/github/Molvilada/Compiladores/blob/main/Primer%20conjunto%20de%20ejercicios/Anexos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Ejercicio 3.4.3

In [ ]:
def failureFunction(substring):
    t = 0
    arr = np.ones(len(substring), dtype=int) 
    arr[0] = 0
    for s in range(1, len(substring)):  
      while(t > 0 and substring[s] != substring[t]):
        t = arr[t - 1]
      if(substring[s] == substring[t]):
        t += 1
        arr[s] = t
      else:
        arr[s] = 0
    return arr

In [ ]:
print(failureFunction("abababaab"))
print(failureFunction("aaaaaa"))
print(failureFunction("abbaabb"))

[0 0 1 2 3 4 5 1 2]
[0 1 2 3 4 5]
[0 0 0 1 1 2 3]



#Ejercicio 3.4.6

In [ ]:
def kmp(substring, string):
  arr = failureFunction(substring)    
  print(arr)
  s = 0
  for i in range(1, len(string)): 
      while(s > 0 and string[i] != substring[s]):
          s = arr[s-1]
      if(string[i] == substring[s]):
          s += 1
      if(s == len(substring)):
          return True

  return False

In [ ]:
substring = "ababaa"
string = "abababaab"
print(kmp(substring, string))

True


In [ ]:
string = "abababbaa"
print(kmp(substring, string))

False


# Ejercicio 3.4.9


In [ ]:
# Punto b
print(failureFunction("abaababa"))

# Punto c
print(failureFunction("abaababaabaab"))


[0 0 1 1 2 3 2 3]
[0 0 1 1 2 3 2 3 4 5 6 4 5]


In [ ]:
substring = "abaababa"
string = "abaababaabaab"
print(kmp(substring, string))

[0 0 1 1 2 3 2 3]
False
